# Generated by Django 4.2.30 on 2026-06-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_inscripcion_acceso_alumno_habilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('pre_inscrito', 'Pre-inscrito'), ('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('baja', 'Baja')], default='pre_inscrito', max_length=20),
        ),
    ]
