# Generated by Django 4.2.30 on 2026-07-05 07:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_alter_actividad_tipo'),
        ('inscripciones', '0005_alter_inscripcion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionRoommateSolicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumno_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_roommate_recibidas', to='inscripciones.alumno')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_roommate', to='viajes.hotel')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommates_solicitados', to='inscripciones.inscripcion')),
            ],
            options={
                'verbose_name': 'Solicitud de Roommate',
                'ordering': ['-created_at'],
                'unique_together': {('inscripcion', 'alumno_solicitado', 'hotel')},
            },
        ),
        migrations.CreateModel(
            name='InscripcionHotelPreferencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_habitacion', models.CharField(choices=[('doble', 'Doble'), ('triple', 'Triple'), ('cuadruple', 'Cuadruple'), ('sin_preferencia', 'Sin preferencia')], default='sin_preferencia', max_length=20)),
                ('tipo_cama', models.CharField(choices=[('individuales', 'Camas individuales separadas'), ('compartida', 'Cama doble compartida'), ('sin_preferencia', 'Sin preferencia')], default='sin_preferencia', max_length=20)),
                ('planta', models.CharField(choices=[('baja', 'Planta baja'), ('alta', 'Planta alta'), ('sin_preferencia', 'Sin preferencia')], default='sin_preferencia', max_length=20)),
                ('necesidades_especiales', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente confirmacion agencia'), ('confirmado', 'Confirmado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_inscripciones', to='viajes.hotel')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_hotel', to='inscripciones.inscripcion')),
            ],
            options={
                'verbose_name': 'Preferencia de Hotel',
                'ordering': ['-created_at'],
                'unique_together': {('inscripcion', 'hotel')},
            },
        ),
    ]
