# Generated by Django 4.2.30 on 2026-07-09 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logauditoria',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Log de Auditoría', 'verbose_name_plural': 'Logs de Auditoría'},
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='accion',
            field=models.CharField(help_text='PAGO_REGISTRADO, PAGO_ACTUALIZADO, DOCUMENTO_VALIDADO, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP del request', null=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='modelo',
            field=models.CharField(help_text='Nombre del modelo afectado', max_length=100),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='objeto_id',
            field=models.UUIDField(blank=True, help_text='ID del objeto afectado', null=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Cuándo ocurrió la acción'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='valor_anterior',
            field=models.JSONField(blank=True, help_text='Estado previo (snapshot)', null=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='valor_nuevo',
            field=models.JSONField(blank=True, help_text='Estado posterior (snapshot)', null=True),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['usuario', 'timestamp'], name='auditoria_l_usuario_2e2fec_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['modelo', 'objeto_id'], name='auditoria_l_modelo_c5c06d_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['accion', 'timestamp'], name='auditoria_l_accion_56b9d7_idx'),
        ),
    ]
