# Generated by Django 4.2.30 on 2026-06-28 18:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itinerario', to='viajes.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='EtapaItinerario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='itinerarios/etapas/')),
                ('itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='viajes.itinerario')),
            ],
            options={
                'ordering': ['dia_numero'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(blank=True, choices=[('vuelo', 'Vuelo / Traslado aéreo'), ('bus', 'Transporte terrestre'), ('hotel', 'Alojamiento / Check-in'), ('comida', 'Comidas (Desayuno, Almuerzo, Cena)'), ('excursion', 'Excursión / Tour'), ('libre', 'Tiempo libre'), ('otro', 'Otra actividad')], max_length=20, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='viajes.etapaitinerario')),
            ],
            options={
                'ordering': ['orden', 'hora'],
            },
        ),
        migrations.AddConstraint(
            model_name='etapaitinerario',
            constraint=models.UniqueConstraint(fields=('itinerario', 'dia_numero'), name='unique_etapa_por_itinerario'),
        ),
    ]
