# Generated by Django 4.2.30 on 2026-06-28 18:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_itinerario_etapaitinerario_actividad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tasa_turistica', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fianza', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('web_url', models.URLField(blank=True, default='', max_length=500)),
                ('maps_url', models.URLField(blank=True, default='', max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='hoteles/')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoteles', to='viajes.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, default='', max_length=300)),
                ('capacidad', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='viajes.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoRequerido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('obligatorio', models.BooleanField(default=True)),
                ('formatos_permitidos', models.CharField(default='pdf,jpg,png', max_length=100)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_requeridos', to='viajes.viaje')),
            ],
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('viaje', 'nombre'), name='unique_grupo_por_viaje'),
        ),
    ]
