# Generated by Django 4.2.30 on 2026-07-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_viaje_colegio_viaje_grado_viaje_nivel_educativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(blank=True, choices=[('vuelo', 'Vuelo / Traslado aéreo'), ('bus', 'Transporte terrestre'), ('hotel', 'Alojamiento / Check-in'), ('comida', 'Comidas (Desayuno, Almuerzo, Cena)'), ('excursion', 'Excursión / Tour'), ('libre', 'Tiempo libre'), ('otro', 'Otra actividad')], max_length=20, null=True),
        ),
    ]
