# Generated by Django 4.2.30 on 2026-07-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_alter_actividad_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='aerolinea',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='actividad',
            name='numero_vuelo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
