# Generated by Django 4.2.30 on 2026-07-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0006_actividad_aerolinea_actividad_numero_vuelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='destino',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='actividad',
            name='hora_llegada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='origen',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='actividad',
            name='puerta_embarque',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='actividad',
            name='terminal',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
