# Generated by Django 4.2.30 on 2026-07-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0007_actividad_destino_actividad_hora_llegada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
