# Generated by Django 4.2.30 on 2026-07-12 06:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0006_inscripcionroommatesolicitud_and_more'),
        ('colegios', '0001_initial'),
        ('viajes', '0008_hotel_latitud_hotel_longitud_hotel_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('seguro', 'Seguro'), ('menu', 'Menú especial'), ('actividad_opcional', 'Actividad opcional'), ('extra', 'Extra')], max_length=30)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Complemento',
                'verbose_name_plural': 'Complementos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='viaje',
            name='colegio_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='colegios.colegio'),
        ),
        migrations.CreateModel(
            name='ComplementoViaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('complemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.complemento')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complementos', to='viajes.viaje')),
            ],
            options={
                'verbose_name': 'Complemento por viaje',
                'verbose_name_plural': 'Complementos por viaje',
                'unique_together': {('viaje', 'complemento')},
            },
        ),
        migrations.CreateModel(
            name='ComplementoContratado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complemento_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.complementoviaje')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complementos_contratados', to='inscripciones.inscripcion')),
            ],
            options={
                'verbose_name': 'Complemento contratado',
                'verbose_name_plural': 'Complementos contratados',
            },
        ),
    ]
